name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  example:
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["14.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build example
        run: make build-example